### ISSUE TITLE
Förstasida TODO

### ISSUE THREAD

**Issue by almbr** [ETAChalmers/ETA-Hemsida-3.0#1]
Todo för förtasidan 'Home'. 

Mitt förslag till Layout:
- Header
- Kort introduktion av ETA
- Kort info om auktionen
- Info om hur man blir medlem
- Info om hur man tar sig till ETA. Med ̣~~Google Maps~~ OpenStreetMap till ETAs adress. 

**Todo**
- [X] Bestäm layout.
- [x] Gör introtext-sektion.
- [x] Skriv text till introtext.
- [ ] Gör auktion-sektion.
- [x] Skriv text till auktion-sektion.
- [ ] Hitta en bättre, högre upplöst, auktionsbild.
- [ ] Gör bli medlem-sektion.
- [ ] Skriv text till bli medlem-sektion.
- [ ] Gör hitta hit-sektion.
- [ ] Skriv text till hitta hit-sektion.
- [x] Gör Google Maps-sektion.
